
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-5
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-5
pull_requests: [{"author":{"id":"U_kgDOBdCCBA","is_bot":false,"login":"jasontnguyen","name":"Jason Nguyen"},"headRefName":"JN-RecommendationRequest-backend","number":66,"title":"Copy RecommendationRequest Files For Backend","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/66"},{"author":{"id":"U_kgDOBdHhNQ","is_bot":false,"login":"GarvinYoung","name":""},"headRefName":"GY-Articles-Form","number":65,"title":"Created Form for Articles + Tests and Story","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/65"},{"author":{"id":"U_kgDOBdHhNQ","is_bot":false,"login":"GarvinYoung","name":""},"headRefName":"GY-Articles-Fixtures","number":64,"title":"Added Fixtures for Articles","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/64"},{"author":{"id":"U_kgDOBdHhNQ","is_bot":false,"login":"GarvinYoung","name":""},"headRefName":"GY-Articles-CopyCRUD","number":63,"title":"Articles Copying CRUD operations from Team02","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/63"}]
