
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-5
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-5
pull_requests: [{"author":{"id":"U_kgDOBckqqw","is_bot":false,"login":"CongruiDu","name":"RayDu"},"headRefName":"RD-tests","number":117,"title":"RD-H05 Integration tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/117"},{"author":{"id":"U_kgDOBXcy6w","is_bot":false,"login":"winstonwangUCSB","name":""},"headRefName":"WW-HelpRequest-HW05","number":116,"title":"HelpRequest HW05","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/116"},{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"SL-Integration","number":115,"title":"MenuItemReview HW05","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/115"},{"author":{"id":"U_kgDOBdHhNQ","is_bot":false,"login":"GarvinYoung","name":""},"headRefName":"GY-Articles-HW05","number":114,"title":"Articles HW05","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/114"},{"author":{"id":"U_kgDOBdCCBA","is_bot":false,"login":"jasontnguyen","name":"Jason Nguyen"},"headRefName":"JN-RecommendationRequest-h05","number":98,"title":"RecommendationRequest-HW05","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/98"}]
