
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-5
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-5
pull_requests: [{"author":{"id":"U_kgDOBXcy6w","is_bot":false,"login":"winstonwangUCSB","name":""},"headRefName":"WW-HelpRequest-FormsTablesandPages","number":113,"title":"WW- Adds HelpRequest Table, Form, Create, Edit and Index ","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/113"},{"author":{"id":"U_kgDOBnFWjw","is_bot":false,"login":"Baimin-Wang","name":""},"headRefName":"BW-MenuItem-Index","number":111,"title":"Index Page for UCSB DiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/111"},{"author":{"id":"U_kgDOBnFWjw","is_bot":false,"login":"Baimin-Wang","name":""},"headRefName":"BW-MenuItem-Create","number":109,"title":"Create Page for UCSBDiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/109"},{"author":{"id":"U_kgDOBdCCBA","is_bot":false,"login":"jasontnguyen","name":"Jason Nguyen"},"headRefName":"JN-RecommendationRequest-h05","number":98,"title":"RecommendationRequest-HW05","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/98"}]
