
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-5
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-5
pull_requests: [{"author":{"id":"U_kgDOBckqqw","is_bot":false,"login":"CongruiDu","name":"RayDu"},"headRefName":"RD-Organization-form","number":92,"title":"Form Component for UCSBOrganization plus tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/92"},{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"SL-MenuItemReview-CreatePage","number":91,"title":"Added Create Page For MenuItemReview and Tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/91"},{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"SL-MenuItemReview-Pages","number":90,"title":"Implemented Placeholder Pages for MenuItemReview","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/90"},{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"SL-MenuItemReview-Tables","number":88,"title":" Implemented MenuItemReview Tables & Tests ","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/88"},{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"SL-MenuItemReview-Forms","number":87,"title":"Added MenuItemReview Forms","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/87"},{"author":{"id":"U_kgDOBckqqw","is_bot":false,"login":"CongruiDu","name":"RayDu"},"headRefName":"RD-Organization-fixture","number":77,"title":"Create fixtures for UCSBOrganization","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/77"},{"author":{"id":"U_kgDOBckqqw","is_bot":false,"login":"CongruiDu","name":"RayDu"},"headRefName":"RD-Organization-table","number":74,"title":"Copy files for Backend CRUD API UCSBOrganization from team02","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/74"},{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"SL-Fixtures","number":68,"title":"Implemented MenuItemReview Fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/68"},{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"SL-MenuItemReview-Backend","number":67,"title":"Copy MenuItemReview files for backend ","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-5/pull/67"}]
